# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orba:
  codecov: codecov/codecov@1.0.2
jobs:
  Hello-World:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello World
          command: |
            echo 'Hello World'
            echo 'This us the delivery pipeline'
  I-Have-Code:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code has arrived
          command: |
            ls -la
            echo '^^^ This should look familiar'
  Run-Tests-With-Node:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: install and run tests
          command: |
            npm install && npm test
      - codecov/upload:
          file: ''./coverage/clover.xml'
          token: a680f0ba-8395-4318-81c6-bd95abc94a5d
  Now-Complete:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Approval Complete
          command: |
            echo 'Do work once the approval has completed'
workflows:
  version: 2
  Example_Workflow:
    jobs:
      - Hello-World
      - I-Have-Code:
          requires:
            - Hello-World
      - Run-Tests-With-Node:
          requires:
            - Hello-World
      - Hold-For-Approval:
          type: approval
          requires:
            - Run-Tests-With-Node
            - I-Have-Code
      - Now-Complete:
          requires:
            - Hold-For-Approval
