# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: The first Step
          command: |
            echo 'Hello World'
            echo 'This us the delivery pipeline'
      - run:
          name: Code has arrived
          command: |
            ls -al
            echo '^^^ This should look famimiliar'
